backend:
  name: git-gateway
  repo: chandrabhankadera/website
  branch: main
media_folder: 'assets/uploads'
collections:
    - name: 'blog'
      label: 'Blog'
      folder: '_posts/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
        preview: false
      fields:
        - label: 'Layout'
          name: 'layout' 
          widget: 'hidden'
          default: 'post'
        - label: 'Title'
          name: 'title'
          widget: 'string'
        - label: 'Publish Date'
          name: 'date'
          widget: 'datetime'
        - label: 'Categories'
          name: 'categories'
          multiple: true
          widget: "relation"
          collection: "blogoptions"
          file: "categories"
          search_fields: ["categories.*.title"]
          display_fields: ["categories.*.title"]
          value_field: "categories.*.title"
        - label: 'Tags'
          name: 'tags'
          multiple: true
          widget: "relation"
          collection: "blogoptions"
          file: "tags"
          search_fields: ["tags.*.title"]
          display_fields: ["tags.*.title"]
          value_field: "tags.*.title"
        - label: 'Author'
          name: 'author'
          widget: 'relation'
          collection: 'author'
          display_fields: [display_name]
          search_fields: [display_name]
          value_field: 'name'
        - label: 'Body'
          name: 'body'
          widget: 'markdown'
        - label: 'Post image'
          name: 'image'
          widget: 'image'
          
    - name: 'blogoptions'
      label: 'Blog Options'
      delete: false # Prevent users from deleting documents in this collection
      editor:
        preview: false
      files:
        - name: 'categories'
          label: 'Categories'
          file: '_data/categories.yml'
          description: 'List of categories'
          fields:
            - name: 'categories'
              label: 'Categories'
              label_singular: 'Category'
              widget: list
              fields:
                - { label: 'Title', name: 'title', widget: 'string', hint: 'Enter title' }
                - { label: 'Description', name: 'description', widget: 'markdown' }
        - name: 'tags'
          label: 'Tags'
          file: '_data/tags.yml'
          description: 'List of tags'
          fields:
            - name: 'tags'
              label: 'Tags'
              label_singular: 'Tag'
              widget: list
              fields:
                - { label: 'Title', name: 'title', widget: 'string', hint: 'Enter title' }
                - { label: 'Description', name: 'description', widget: 'markdown' } 
      
    - name: 'author'
      label: 'Authors'
      folder: '_author/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{name}}'
      editor:
        preview: false
      fields:
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
        - { label: 'Short Name', name: 'name', widget: 'string' }
        - { label: 'Display Name', name: 'display_name', widget: 'string' }
        - { label: 'Position', name: 'position', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - label: "Social Links"
          name: "social"
          widget: "object"
          collapsed: true
          fields: 
            - {label: "Facebook", name: "facebook", widget: "string", required: false}
            - {label: "Instagram", name: "instagram", widget: "string", required: false}
            - {label: "Twitter", name: "twitter", widget: "string", required: false}
            - {label: "Github", name: "github", widget: "string", required: false}
    - name: 'testimonial'
      label: 'Testimonials'
      folder: '_testimonial/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{name}}'
      editor:
        preview: false
      fields:
        - label: 'Layout'
          name: 'layout'
          widget: 'hidden'
          default: 'testimonial'
        - label: 'Full Name'
          name: 'name'
          widget: 'string'
        - label: 'Position'
          name: 'position'
          widget: 'string'
        - label: 'Country'
          name: 'country'
          widget: 'string'
        - label: 'Testimonial'
          name: 'body'
          widget: 'markdown'
  
    - name: 'nearby'
      label: 'Nearbyplace'
      folder: '_nearby/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
        preview: false
      fields:
        - label: 'Layout'
          name: 'layout'
          widget: 'hidden'
          default: 'nearby'
        - label: 'Title'
          name: 'title'
          widget: 'string'
        - label: 'Description'
          name: 'description'
          widget: 'string'
        - label: 'Projet URL'
          name: 'project_url'
          widget: 'string'
        - label: 'completed on'
          name: 'completed_on'
          widget: 'date'
        - label: 'Publish Date'
          name: 'date'
          widget: 'datetime'
        - label: 'Body'
          name: 'body'
          widget: 'markdown'
        - label: 'Featured Image'
          name: 'image'
          widget: 'image'
          allow_multiple: true
        - label: 'Video'
          name: 'video'
          widget: 'string'
          required: false
        - label: 'Categories'
          name: 'categories'
          multiple: true
          widget: "relation"
          collection: "nearbyplaces"
          file: "nearbycategories"
          search_fields: ["categories.*.title"]
          display_fields: ["categories.*.title"]
          value_field: "categories.*.title"
        - label: 'Nearbyplaces'
          name: 'nearbyplaces'
          multiple: true
          widget: "relation"
          collection: "nearbyplaces"
          file: "nearbyplaces"
          search_fields: ["nearbyplaces.*.title"]
          display_fields: ["nearbyplaces.*.title"]
          value_field: "nearbyplaces.*.title"
        - label: "Gallery"
          name: "galleryImages"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}
        - label: 'Android App'
          name: 'android'
          widget: 'string'
          required: false
        - label: 'iOS App'
          name: 'ios'
          widget: 'string'
          required: false
          
    - name: 'nearbyplaces'
      label: 'Near Options'
      delete: false # Prevent users from deleting documents in this collection
      editor:
        preview: false
      files:
        - name: 'nearbyplaces'
          label: 'Nearbyplaces'
          file: '_data/nearbyplaces.yml'
          description: 'List of Nearbyplaces'
          fields:
            - name: 'nearbyplaces'
              label: 'Nearbyplaces'
              label_singular: 'Nearbyplace'
              widget: list
              fields:
                - { label: 'Title', name: 'title', widget: 'string', hint: 'Enter title' }
                - { label: 'Description', name: 'description', widget: 'markdown' }
        - name: 'nearbycategories'
          label: 'Nearbyplace categories'
          file: '_data/nearbycategories.yml'
          description: 'List of Nearbyplace categories'
          fields:
            - name: 'categories'
              label: 'Nearbyplace categories'
              label_singular: 'Category'
              widget: list
              fields:
                - { label: 'Title', name: 'title', widget: 'string', hint: 'Enter title' }
                - { label: 'Description', name: 'description', widget: 'markdown' }